**Introduction**

Programme NumPy pour obtenir la version numpy et afficher la configuration de build numpy

In [3]:
import numpy as np
print(np.__version__)
print(np.show_config())

ModuleNotFoundError: No module named 'numpy'

In [ ]:
pip install numpy


Compréhension des éléments de base d'un array

In [ ]:
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print out the shape of `my_array`
print(my_2d_array.shape)
print(" ")

# Print out the data type of `my_array`
print(my_2d_array.dtype)
print(" ")

# Print out the stride of `my_array`
print(my_2d_array.strides)
print(" ")

# Print the number of elements
print(my_2d_array.size)
print(" ")

Notion de copie en Numpy, comparez les deux situations suivantes

In [ ]:

a=np.array([1, 2, 3, 4])
b= np.copy(a) 
b[0]=2
print(b)
print(a)

In [ ]:
a=np.array([1, 2, 3, 4])
b= a
b[0]=2
print(b)
print(a)

Un array peut contenir toutes sortes d'éléments

In [ ]:
 np.array([True ,False ,True], dtype=bool)


Nous allons maintenant regarder comment sauver un array, et identifier où nous l'avons sauvé

In [ ]:
pwd()

In [ ]:
a=np.array([1, 2, 3, 4])
np.save( , a)

Programme NumPy pour obtenir de l'aide sur la fonction d'ajout

In [ ]:
print(np.info(np.all))

La suppression d'éléments dans un array, cela peut servir ...

In [ ]:
# Créer un tableau NumPy
original_array = np.array([1, 2, 3, 4, 5])

# Supprimer l'élément à la position 3
deleted_array = np.delete(original_array, 3)

# Afficher le tableau résultant
print("Tableau après suppression :\n", deleted_array)

Idem pour l'insertion d'un élément (on peut définir où réaliser l'insertion)

In [ ]:
# Créer un tableau NumPy
original_array = np.array([1, 2, 3, 4, 5])

# Insérer la valeur 10 à la position 2
inserted_array = np.insert(original_array, 2, 10)

# Afficher le tableau résultant
print("Tableau après insertion :\n", inserted_array)

Programme NumPy pour tester si aucun des éléments d'un tableau donné n'est nul ou correspond à un False

In [ ]:
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0, 1, 2, 3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([False, True, True])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([True, True, True])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Programme NumPy pour tester s'il existe un élément non nul ou correspondant à un True

In [ ]:
x = np.array([1, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))

Programme NumPy pour tester la finitude des élements d'un tableau donné, élément par élément (pas l'infini ou pas un NaN)

In [ ]:
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))

Programme NumPy pour tester élément par élément l'infini positif ou négatif

In [ ]:
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(a))

Programme NumPy pour tester élément par élément si NaN dans un tableau donné.

In [ ]:
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))

Programme NumPy pour tester si deux tableaux sont égaux élément par élément, avec une certaine tolérance. Au fait, quel argument correspond à quoi ?

In [ ]:
print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10, 1e-7], [1.00001e10, 1e-8]))
print(np.allclose([1e10, 1e-8], [1.00001e10, 1e-9]))
print(np.allclose([1e10, 1e-8], [1.0001e10, 1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

A comparer avec ceci :

In [ ]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Programme NumPy pour créer une comparaison élément par élément (plus grand, plus grand_ou égal, moins grand et moins grand_ou égal) de deux tableaux donnés.

In [ ]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Vérifions si des valeurs sont bien dans un array

In [ ]:

# Créer un tableau NumPy
array = np.array([1, 2, 3, 4, 5])

# Créer un ensemble de valeurs à vérifier
values_to_check = np.array([2, 4, 6])

# Utiliser np.isin pour vérifier l'appartenance des éléments du tableau à l'ensemble de valeurs
result = np.isin(array, values_to_check)

# Afficher le tableau de booléens résultant
print("Tableau de booléens résultant :\n", result)


Programme NumPy pour trouver les indices des valeurs maximales et minimales le long de l'axe donné d'un tableau.

Tableau d'origine : [1 2 3 4 5 6]

Valeurs maximales : 5

Valeurs minimales : 0

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ", x)
print("Maximum Values: ", np.argmax(x))
print("Minimum Values: ", np.argmin(x))

Programme NumPy pour trouver le 4ème élément d'un tableau spécifié.

[[ 2  4  6]

[ 6  8 10]]

Quatrième élément du tableau :

6

In [ ]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
e1 = x.flat[3]
print("Forth e1ement of the array:")
print(e1)

**Génération de données**

Programme NumPy pour créer un tableau avec les valeurs 1, 7, 13, 105 et déterminer la taille de la mémoire occupée par le tableau.

In [ ]:
X = np.array([1, 7, 13, 105])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Programme NumPy pour créer un tableau de 10 zéros, un de 10 uns,  un de 10 cinq.

In [ ]:
array = np.zeros(10)
print("An array of 10 zeros:")
print(array)
array = np.ones(10)
print("An array of 10 ones:")
print(array)
array = np.ones(10)*5
print("An array of 10 fives:")
print(array)

Programme NumPy pour créer un tableau d'entiers allant de 30 à 70

In [ ]:
array = np.arange(30, 71)
print("Array of the integers from 30 to70")
print(array)


Programme NumPy pour créer un tableau d'entiers allant de 30 à 70, de deux en deux

In [ ]:
array = np.arange(30, 71, 2)
print("Array of all the even integers from 30 to 70")
print(array)

Programme NumPy pour créer une matrice d'identité 3x3

In [ ]:
array_2D = np.identity(3)
print('3x3 matrix:')
print(array_2D)

Programme NumPy pour générer un nombre aléatoire entre 0 et 1, pris au sein d'une distribution normale

In [ ]:
rand_num = np.random.normal(0, 1, 1)
print("Random number between 0 and 1:")
print(rand_num)

Programme NumPy pour générer une séquence de nombres aléatoires pris entre 0 et 1, au sein d'une distribution normale

In [ ]:
rand_num = np.random.normal(0, 1, 15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

Programme NumPy pour créer un vecteur de longueur 5 rempli d'entiers choisis arbitrairement entre 0 et 10.

In [ ]:
x = np.random.randint(0, 11, 5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)

 NumPy pour créer un vecteur avec des valeurs allant de 15 à 55 et visionner toutes les valeurs sauf la première et la dernière

In [ ]:
v = np.arange(15, 55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])

Programme NumPy pour créer un tableau 3X4 en l'utilisant et itérer en son sein

In [ ]:
a = np.arange(10, 22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
    print(x, end=" ")
    

Programme NumPy pour créer un vecteur de longueur 10 avec des valeurs uniformément réparties entre 5 et 50

In [ ]:
v = np.linspace(10, 49, 5)
print("Length 10 with values evenly distributed between 5 and 50:")
print(v)

Programme NumPy pour convertir des tableaux 1-D sous forme de colonnes en un tableau 2-D.

Exemple de tableau : (10,20,30), (40,50,60)

Production attendue:

[[10 40]

[20 50]

[30 60]]

In [ ]:
a = np.array((10, 20, 30))
b = np.array((40, 50, 60))
c = np.column_stack((a, b))
print(c)

Écrivez un programme NumPy pour diviser un tableau de 14 éléments en 3 tableaux, dont chacun comprenant 2, 4 et 8 éléments dans l'ordre d'origine.

Production attendue:

Tableau d'origine : [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]

Après le fractionnement :

[array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

In [ ]:
x = np.arange(1, 15)
print("Original array:", x)
print("After splitting:")
print(np.split(x, [2, 6]))

Réalisation d'un vertical split : quelle spécificité par rapport à la colonne précédente

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print("Original Array:")
print(arr)
sub_arrays = np.vsplit(arr, 3)
print(sub_arrays )

Comprendre pourquoi np.partition peut être utilisé pour ordonner un array, et comment sélectionner un certain nombre des valeurs les plus élevées

In [ ]:
n=5 #Que se passe-t-il quand l'on fait évoluer la valeur de n ? Et pourquoi ?
np.array([3, 1, 2, 4, 5])
np.partition(arr,-n)

In [ ]:
arr = np.array([3, 1, 2, 4, 5])
n = 3
print(np.partition(arr, -n)[-n:])



Création d'une meshgrid

In [ ]:
# Import NumPy and Matplotlib
import numpy as np
import matplotlib.pyplot as plt

# Create an array
points = np.arange(-5, 5, 0.01)

# Make a meshgrid
xs, ys = np.meshgrid(points, points)
z = np.sqrt(xs ** 2 + ys ** 2)

# Display the image on the axes
plt.imshow(z, cmap=plt.cm.gray)

# Draw a color bar
plt.colorbar()

# Show the plot
plt.show()

**Manipulation d'arrays - création d'arrays niveau avancé**

Programme NumPy pour créer un vecteur avec des valeurs de 0 à 20 et changer le signe des nombres compris entre 9 et 15

In [ ]:
x = np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
l = [12.23, 13.32, 100, 36.32]
print("Original List:", l)
a = np.array(l)
print("One-dimensional NumPy array: ", a)

Inversez l'ordre des éléments d'un array

Array original:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Array retourné:

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [ ]:
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Écrivez un programme NumPy pour
convertir un tableau en type float. Accédez à l'éditeur
Exemple de sortie :
Tableau d'origine :
[1, 2, 3, 4]
Tableau converti en type float :
[ 1. 2. 3. 4.]

In [ ]:
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Programme NumPy pour changer le type de données d'un tableau. Méthode avec as.type

[[ 2  4  6]

[ 6  8 10]]

Le type de données du tableau x est : int32

Nouveau Type :  float64

[[  2.   4.   6.]

[  6.   8.  10.]]

In [ ]:
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:", x.dtype)
# Change the data type of x
y = x.astype(float)
print("New Type: ", y.dtype)
print(y)

Programme NumPy pour créer un tableau 2D avec 1 sur la bordure et 0 à l'intérieur

In [ ]:
x = np.ones((5, 5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1, 1:-1] = 0
print(x)

Créez un échiquier de 1 et de 0 de 8*8

In [ ]:
x = np.ones((3, 3))
print("Checkerboard pattern:")
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

Illustration du padding autour d'un array

In [ ]:
import numpy as np

# Créer un tableau numpy 2D de forme (3, 4)
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Spécifier le nombre de zéros à ajouter de chaque côté
pad_width = ((1, 2), (2, 1))  # ((haut, bas), (gauche, droite))

# Ajouter du padding en utilisant np.pad
padded_array = np.pad(original_array, pad_width, mode='constant', constant_values=0)

print("Tableau original :\n", original_array)
print("\nTableau avec padding :\n", padded_array)


Écrivez un programme NumPy pour convertir une liste et un tuple en tableaux

In [ ]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))

Écrivez un programme NumPy pour ajouter des valeurs à la fin d'un tableau.
Production attendue:
Tableau d'origine :
[10, 20, 30]
Après avoir ajouté les valeurs à la fin du tableau :
[10 20 30 40 50 60 70 80 90]

In [ ]:
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)

Création d'un array vide, puis d'un array plein

In [ ]:
# Create an empty array
x = np.empty((3, 4))
print(x)
print('')
# Create a full array
y = np.full((3, 3), 6)
print(y)

Programme NumPy pour créer un tableau 3 D avec des uns sur une diagonale et des zéros ailleurs. Jouez un peu avec les dimensions

Production attendue:

[[ 1. 0. 0.]

[ 0. 1. 0.]

[ 0. 0. 1.]]

In [ ]:
np.eye(3,3)

Programme NumPy pour créer un tableau 2D dont la diagonale est égale à [4, 5, 6, 8] et 0 ailleurs .

Production attendue:

[[4 0 0 0]

[0 5 0 0]

[0 0 6 0]

[0 0 0 8]]

In [ ]:
x = np.diagflat([4, 5, 6, 8])
print(x)

Programme NumPy pour échanger deux axes d'un tableau.

Exemple de résultat :

[[1 2 3]]

[[1]

[2]

[3]]

In [ ]:
x = np.array([[1, 2, 3]])
print(x)
print(' ')
y = np.swapaxes(x, 0, 1)
print(y)

Programme NumPy pour rendre un tableau immuable (lecture seule).

Production attendue:

Testez si le tableau est en lecture seule ou non :

Essayez de changer la valeur du premier élément :

Traceback (dernier appel le plus récent) :

Fichier "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", ligne 6, dans

x[0] = 1

ValueError : la destination de l'attribution est en lecture seule

In [ ]:
x = np.zeros(10)
x.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
x[0] = 1

Programme NumPy pour créer un tableau de zéros et trois types de colonnes (entier, flottant, caractère).

[(1,  2., b'Albert Einstein') (2,  2., b'Edmond Halley')

(3,  3., b'Gertrude B. Elion')]

In [ ]:
x = np.zeros((3,), dtype=('i4,f4,a40'))
new_data = [(1, 2., "Albert Einstein"), (2, 2., "Edmond Halley"),
            (3, 3., "Gertrude B. Elion")]
x[:] = new_data
print(x)

**Opérations logico-mathématiques**

Programme NumPy pour tester si chaque élément d'un tableau 1-D est également présent dans un deuxième tableau.

Production attendue:

Tableau 1 : [ 0 10 20 40 60]

Tableau 2 : [0, 40

Comparez chaque élément du tableau 1 et du tableau 2

[ Vrai Faux Faux Vrai Faux]

In [ ]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ", array1)
array2 = [0, 40]
print("Array2: ", array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Programme NumPy pour trouver des valeurs communes entre deux tableaux.

Production attendue:

Tableau 1 : [ 0 10 20 40 60]

Tableau 2 : [10, 30, 40]

Valeurs communes entre deux tableaux :

[10 40]

In [ ]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ", array1)
array2 = [10, 30, 40]
print("Array2: ", array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Programme NumPy pour trouver la différence définie de deux tableaux. La différence définie renverra les valeurs triées et uniques dans le tableau 1 qui ne ne ne pas dans le tableau2.

Production attendue:

Tableau 1 : [ 0 10 20 40 60 80]

Tableau 2 : [10, 30, 40, 50, 70, 90]

Définir la différence entre deux tableaux :

[ 0 20 60 80]

In [ ]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ", array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ", array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Programme NumPy pour trouver l'ensemble ou-exclusif de deux tableaux. Définir exclusif-ou renverra les valeurs uniques triées qui sont dans un seulement (pas les deux) des tableaux d'entrée.

Tableau 1 : [ 0 10 20 40 60 80]

Tableau 2 : [10, 30, 40, 50, 70]

Valeurs uniques qui sont dans un seulement un (pas les deux) des tableaux d'entrée :

[ 0 20 30 50 60 70 80]

In [ ]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ", array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ", array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))


Programme NumPy pour trouver l'union de deux tableaux. Union renverra le tableau unique et trié de valeurs qui sont dans l'un des deux tableaux d'entrée.

Tableau 1 : [ 0 10 20 40 60 80]

Tableau 2 : [10, 30, 40, 50, 70]

Tableau trié unique de valeurs qui se dans l'un des deux tableaux d'entrée :

[ 0 10 20 30 40 50 60 70 80]

In [ ]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ", array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ", array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2))

Programme NumPy pour calculer les valeurs moyennes de deux tableaux NumPy donnés.

Exemple de résultat :

Tableaux d'origine :

[[0, 1], [2, 3]]

[[4, 5], [0, 3]]

Valeurs moyennes de deux tableaux NumPy :

[[2. 3.]

[1. 3.]]

In [ ]:
array1 = [[0, 1], [2, 3]]
array2 = [[4, 5], [0, 3]]
print("Original arrays:")
print(array1)
print(array2)
print("Average values of two said numpy arrays:")
result = (np.array(array1) + np.array(array2)) / 2
print(result)

Programme NumPy pour calculer la somme de toutes les colonnes d'un tableau NumPy 2D.

Exemple de résultat :

Tableau d'origine :

[[ 0 1 2 3 4 5 6 7 8]

[ 9 10 11 12 13 14 15 16 17]

[18 19 20 21 22 23 24 25 26]

[27 28 29 30 31 32 33 34 35]]

Somme de toutes les colonnes :

[54 58 62 66 70 74 78 82 86]

In [ ]:
num = np.arange(36)
arr1 = np.reshape(num, [4, 9])
print("Original array:")
print(arr1)
result = arr1.sum(axis=0)
print("\nSum of all columns:")
print(result)

**Wrangling (un peu plus) avancé**

Aplatir l'array 2*2 de votre choix avec np.ravel

Écrivez un programme NumPy pour échanger des colonnes dans un tableau donné.

Tableau d'origine :

[[ 0  1  2  3]

[ 4  5  6  7]

[ 8  9 10 11]]

Après avoir échangé les tableaux :

[[ 1  0  2  3]

[ 5  4  6  7]

[ 9  8 10 11]]

In [ ]:
my_array = np.arange(12).reshape(3, 4)
print("Original array:")
print(my_array)
my_array[:, [0, 1]] = my_array[:, [1, 0]]
print("\nAfter swapping arrays:")
print(my_array)

In [ ]:
x = np.array([24, 27, 30, 29, 18, 14])
print("Original array:")
print(x)
y = np.empty_like(x)
y[:] = x
print("\nCopy of the said array:")
print(y)

Maintenant, jouez avec le code suivant, que constatez-vous ?

In [ ]:
y[0]=0
y=x
x

Programme NumPy pour extraire tous les éléments des deuxième et troisième colonnes d'un tableau (4x4) donné.

Exemple de résultat :

Tableau d'origine :

[[ 0 1 2 3]

[ 4 5 6 7]

[ 8 9 10 11]

[12 13 14 15]]

Données extraites : Tous les éléments des deuxième et troisième colonnes

[[ 1 2]

[ 5 6]

[ 9 10]

[13 14]]

In [ ]:
arra_data = np.arange(0, 16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: All the elements of the second and third columns")
print(arra_data[:, [1, 2]])

Programme NumPy pour empiler des tableaux en séquence horizontalement (par colonne ).

Exemple de résultat :

Tableaux d'origine :

Tableau-1

[[0 1 2]

[3 4 5]

[6 7 8]]

Tableau-2

[[ 0 3 6]

[ 9 12 15]

[18 21 24]]

Empilez les tableaux dans l'ordre horizontalement :

[[ 0 1 2 0 3 6]

[ 3 4 5 9 12 15]

[ 6 7 8 18 21 24]]

In [ ]:
print("\nOriginal arrays:")
x = np.arange(9).reshape(3, 3)
y = x*3
print("Array-1")
print(x)
print("Array-2")
print(y)
new_array = np.hstack((x, y))
print("\nStack arrays in sequence horizontally:")
print(new_array)

Transposition d'un array

In [ ]:
import numpy as np
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_2d_array`
print(my_2d_array)

# Transpose `my_2d_array`
print(np.transpose(my_2d_array))

# Or use `T` to transpose `my_2d_array`
print(my_2d_array.T)

Programme NumPy pour calculer le lineplot des éléments d'un array

In [ ]:
arr = np.random.randint(1, 50, 10)
y, x = np.histogram(arr, bins=np.arange(51))
fig, ax = plt.subplots()
ax.plot(x[:-1], y)
fig.show()

**Algèbre linéaire**

Programme NumPy pour calculer la multiplication de deux matrices données.

matrice originale :

[[1, 0], [0, 1]]

[[1, 2], [3, 4]]

Résultat de ladite multiplication matricielle :

[[1 2]

[3 4]]

In [ ]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

Programme NumPy pour calculer le produit externe de deux vecteurs donnés.

matrice originale :

[[1, 0], [0, 1]]

[[1, 2], [3, 4]]

Produit externe desdits deux vecteurs :

[[1 2 3 4]

[0 0 0 0]

[0 0 0 0]

[1 2 3 4]]

In [ ]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result = np.outer(p, q)
print("Outer product of the said two vectors:")
print(result)

Programme NumPy pour calculer le produit vectoriel de deux vecteurs donnés.

In [ ]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("cross product of the said two vectors(p, q):")
print(result1)
print("cross product of the said two vectors(q, p):")
print(result2)

Programme NumPy pour calculer le déterminant d'un tableau carré donné.

Tableau 2D d'origine

[[1 0]

[1 2]]

Déterminant du dit matrice 2-D :

2.0

In [ ]:
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))

Programme NumPy pour trouver une norme matricielle ou vectorielle

In [ ]:
v = np.arange(7)
result = np.linalg.norm(v)
print("Vector norm:")
print(result)
m = np.matrix('1, 2; 3, 4')
result1 = np.linalg.norm(m)
print("Matrix norm:")
print(result1)

Programme NumPy pour calculer la matrice inverse d'une matrice donnée

In [ ]:
m = np.array([[1, 2], [3, 4]])
print("Original matrix:")
print(m)
result = np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)

In [ ]:
m = np.array([[1, 2], [3, 4]])
print("Original matrix:")
print(m)
result = np.linalg.cond(m)
print("Condition number of the said matrix:")
print(result)

Programme NumPy pour calculer la somme des éléments diagonaux d'un tableau donné.

In [ ]:
m = np.arange(6).reshape(2, 3)
print("Original matrix:")
print(m)
result = np.trace(m)
print("Condition number of the said matrix:")
print(result)


Programme NumPy pour obtenir le L triangulaire inférieur dans la décomposition de Cholesky d'un tableau donné.

In [ ]:
a = np.array([[4, 12, -16], [12, 37, -53], [-16, -53, 98]], dtype=np.int32)
print("Original array:")
print(a)
L = np.linalg.cholesky(a)
print("Lower-trianglular L in the Cholesky decomposition of the said array:")
print(L)

Multiplication de matrice avec NumPy

In [ ]:
x = [[1, 0], [1, 1]]
y = [[3, 1], [2, 2]]
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)
print("Matrix product of above two arrays:")
print(np.matmul(x, y))

**Opérations mathématiques**

Programme NumPy pour ajouter, soustraire, multiplier, diviser des arguments par élément.

In [ ]:
from numpy.polynomial import polynomial as P
import numpy as np
print("Add:")
print(np.add(1.0, 4.0))
print("Subtract:")
print(np.subtract(1.0, 4.0))
print("Multiply:")
print(np.multiply(1.0, 4.0))
print("Divide:")
print(np.divide(1.0, 4.0))

Programme NumPy pour diviser les éléments du tableau par élément.

In [ ]:
x = np.arange(10)
print("Original array:")
print(x)
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3))

Programme NumPy pour obtenir le plus grand entier inférieur ou égal à la division des entrées

In [ ]:
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

Passage à la puissance

In [ ]:
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

Obtention de la valeur absolue pour un array

In [ ]:
x = np.array([-10.2, 122.2, .20])
print("Original array:")
print(x)
print("Element-wise absolute value:")
print(np.absolute(x))

Passage à l'arrondi

In [ ]:
x = np.round([1.45, 1.50, 1.55])
print(x)
x = np.round([0.28, .50, .64], decimals=1)
print(x)
x = np.round([.5, 1.5, 2.5, 3.5, 4.5])  # rounds to nearest even value
print(x)

Programme NumPy pour arrondir les éléments du tableau à l'entier le plus proche.

In [ ]:
x = np.array([-.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.0])
print("Original array:")
print(x)
x = np.rint(x)
print("Round elements of the array to the nearest integer:")
print(x)

Entier ingérieur, entier supérieur, valeur tronquée (entier)

In [ ]:
x = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])
print("Original array:")
print(x)
print("Floor values of the above array elements:")
print(np.floor(x))
print("Ceil values of the above array elements:")
print(np.ceil(x))
print("Truncated values of the above array elements:")
print(np.trunc(x))

Programme NumPy pour multiplier une matrice 5x3 par une matrice 3x2 et créer un produit matriciel.

In [ ]:
x = np.random.random((5, 3))
print("First array:")
print(x)
y = np.random.random((3, 2))
print("Second array:")
print(y)
z = np.dot(x, y)
print("Dot product of two arrays:")
print(z)

Recherche des racines d'un polynôme avec NumPy

In [ ]:
print("Roots of the first polynomial:")
print(np.roots([1, -2, 1]))
print("Roots of the second polynomial:")
print(np.roots([1, -12, 10, 7, -10]))

Calculs avec un polynôme

In [ ]:
print(np.polyval([1, -2, 1], 2))
print("Polynomial value when x = 3:")
print(np.polyval([1, -12, 10, 7, -10], 3))

Programme NumPy pour calculer la moyenne sur toute dimension, dans un tableau numpy 2D.

In [ ]:
x = np.array([[10, 30], [20, 60]])
print("Original array:")
print(x)
print("Mean of each column:")
print(x.mean(axis=0))
print("Mean of each row:")
print(x.mean(axis=1))

Faire de même avec la variance et l'écart-type

Imaginez que vous travaillez pour une entreprise qui vend plusieurs produits dans différents pays. Chaque trimestre, cette entreprise enregistre les ventes de chaque produit dans chaque pays. Ces enregistrements sont stockés dans un tableau NumPy, où chaque colonne représente un produit et chaque ligne représente un pays. Les ventes sont cumulées sur l'année, ce qui signifie que chaque pays a 4 lignes (une pour chaque trimestre).

L'entreprise a besoin de plusieurs analyses basées sur les données trimestrielles. Par exemple, elle veut connaître les performances des ventes de chaque produit pour chaque trimestre individuellement, comparer les ventes d'un trimestre à celles du trimestre précédent, ou encore identifier les tendances sur l'année.

In [ ]:
import numpy as np

# Supposons que nous ayons un tableau de données de ventes avec 12 lignes (3 pays * 4 trimestres) et 5 produits
data = np.random.randint(100, 1000, size=(12, 5))

# Nous utilisons np.split pour diviser les données en 4 sous-tableaux (un pour chaque trimestre)
trimestres = np.split(data, 4)

for idx, trimestre in enumerate(trimestres, 1):
    print(f"Ventes du trimestre {idx}:\n{trimestre}\n")


Travaillons un peu avec le concept de modulo

In [ ]:
# Créer un tableau NumPy
array = np.array([10, 20, 30, 40, 50])

# Calculer le reste de la division de chaque élément par 3
remainder_array = np.mod(array, 3)

# Afficher le tableau des restes
print("Tableau des restes de la division par 3 :\n", remainder_array)


Programme NumPy pour calculer le tableau trigonométrique sinus, cosinus et tangent d'angles donnés en degrés

In [ ]:
print("sine: array of angles given in degrees")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("cosine: array of angles given in degrees")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))
print("tangent: array of angles given in degrees")
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

Programme NumPy pour calculer la somme cumulée des éléments le long d'un axe donné, la somme sur les lignes pour chacune des 3 colonnes et la somme sur les colonnes pour chacune des 2 lignes d'un tableau 3x3 donné.

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array: ")
print(x)
print("Cumulative sum of the elements along a given axis:")
r = np.cumsum(x)
print(r)
print("\nSum over rows for each of the 3 columns:")
r = np.cumsum(x, axis=0)
print(r)
print("\nSum over columns for each of the 2 rows:")
r = np.cumsum(x, axis=1)
print(r)

Programme NumPy pour calculer la différence entre les éléments voisins, élément par élément, pour un tableau donné.

In [ ]:
x = np.array([1, 3, 5, 7, 0])
print("Original array: ")
print(x)
print("Difference between neighboring elements, element-wise of the said array.")
print(np.diff(x))

Programme NumPy pour calculer la valeur numérique négative pour tous les éléments d'un tableau donné.

In [ ]:
x = np.array([0, 1, -1])
print("Original array: ")
print(x)
r1 = np.negative(x)
r2 = -x
assert np.array_equal(r1, r2)
print("Numerical negative value for all elements of the said array:")
print(r1)

Programme NumPy pour calculer l'inverse de tous les éléments d'un tableau donné

In [ ]:
x = np.array([1., 2., .2, .3])
print("Original array: ")
print(x)
r1 = np.reciprocal(x)
r2 = 1/x
assert np.array_equal(r1, r2)
print("Reciprocal for all elements of the said array:")
print(r1)

Programme NumPy pour calculer une indication élément par élément du signe pour tous les éléments d'un tableau donné

In [ ]:
x = np.array([1, 3, 5, 0, -1, -7, 0, 5])
print("Original array;")
print(x)
r1 = np.sign(x)
r2 = np.copy(x)
r2[r2 > 0] = 1
r2[r2 < 0] = -1
assert np.array_equal(r1, r2)
print("Element-wise indication of the sign for all elements of the said array:")
print(r1)

Obtention des valeurs minimales et maximales

In [ ]:
a = np.arange(4).reshape((2, 2))
print("Original flattened array:")
print(a)
print("Maximum value of the above flattened array:")
print(np.amax(a))
print("Minimum value of the above flattened array:")
print(np.amin(a))

Programme NumPy pour multiplier les valeurs de deux vecteurs donnés

In [ ]:
x = np.array([1, 8, 3, 5])
print("Vector-1")
print(x)
y = np.random.randint(0, 11, 4)
print("Vector-2")
print(y)
result = x * y
print("Multiply the values of two said vectors:")
print(result)


Programme NumPy pour calculer la différence entre les valeurs maximales et minimales d'un tableau donné le long d'un axe

In [ ]:
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.ptp(x, 1)
r2 = np.amax(x, 1) - np.amin(x, 1)
assert np.allclose(r1, r2)
print("\nDifference between the maximum and the minimum values of the said array:")
print(r1)

**Numpy string operations**

Concatenation : rajoutez simplement des espaces entre les mots concaténés dans le code suivant

In [ ]:
>>> word = "Solution"
>>> another_word = "another solution"
>>> third_word = "3rd solution!"
>>> all_words = word+another_word+third_word
>>> all_words
'Solutionanother solution3rd solution!'

Il y a plusieurs manières de concaténer, une approche un peu plus subtile ...

In [ ]:
array1 = np.array(['Hello', 'World'])
array2 = np.array([', ', 'NumPy'])

# Utiliser np.char.add pour concaténer les chaînes de caractères
concatenated_array = np.char.add(array1, array2)

# Afficher le tableau résultant
print("Tableau concaténé :\n", concatenated_array)

Répétition de strings et découpage

In [ ]:
# Repeat strings with *
3 * "data " # 'data data data '

# Split a string on a delimiter
"beekeepers".split("e") # ['b', '', 'k', '', 'p', 'rs']

Et maintenant, apprenons à compter des répétitions ...

In [ ]:
array = np.array(['Hello, world!', 'Python programming', 'Hello, Python'])

# Utiliser np.char.count pour compter le nombre d'occurrences de la sous-chaîne 'Hello' dans chaque élément
count_array = np.char.count(array, 'Hello')

# Afficher le tableau résultant
print("Tableau de comptage d'occurrences :\n", count_array)

Remplacement, majuscules, minuscules

In [ ]:
# Create a string named str
str = "Jack and Jill"

# Convert a string to uppercase
str.upper() # 'JACK AND JILL'

# Convert a string to lowercase
str.lower() # 'jack and jill'

# Convert a string to title case
str.title() # 'Jack And Jill' 

# Replaces matches of a substring with another
str.replace("J", "P") # 'Pack and Pill'

Exemple d'utilisation d'index dans un string

In [ ]:
s = "Electrical & Electronic Engineering"
print(s[3])
# Slicing the above string
#[start:end:increment]
print(s[0:25:2])

Utilisez les index pour n'avoir que Jack (en partant du début), ou que Jill (en partant d'un index choisi de manière pertinente)

In [ ]:
str = "Jack and Jill"
...

Distinguer lettres et nombres

In [ ]:
a = np.array(['a', 'b', '0'])
np.char.isdigit(a)

a = np.array([['a', 'b', '0'], ['c', '1', '2']])
np.char.isdigit(a)


Quel est l'inverse de isdigit ? Montrez ci-dessous une application 

Longueur d'une string

In [ ]:
a = np.array(['Grace Hopper Conference', 'Open Source Day'])
np.char.str_len(a)

Trouver les strings qui terminent par un pattern. Modifier le code pour vous intéresser à ce qui commence par un pattern

In [ ]:

s = np.array(['foo', 'bar'])
s[0] = 'foo'
s[1] = 'bar'
s

np.char.endswith(s, 'ar')

Pour information, on peut passer d'un string à un array

In [ ]:


# Créer une chaîne de caractères contenant des données binaires (ex. : 8 octets)
binary_data = b'\x01\x02\x03\x04\x05\x06\x07\x08'

# Utiliser np.fromstring pour convertir la chaîne de caractères en un tableau NumPy
numpy_array = np.fromstring(binary_data, dtype=np.uint8)

# Afficher le tableau NumPy résultant
print("Tableau NumPy à partir de la chaîne binaire :\n", numpy_array)

# Vous pouvez maintenant manipuler le tableau NumPy comme vous le souhaitez


Vectorisation d'une string : montons un peu en compétence

In [ ]:
import numpy as np
from collections import Counter

def string_to_vector(str):
    # Count the frequency of each character in the string
    char_freq = Counter(str)
    # Create a vector from the frequencies
    vector = np.zeros(256)  # Assuming ASCII characters
    for char, freq in char_freq.items():
        vector[ord(char)] = freq
    return vector


Testez cette fonction sur un exemple de votre choix, et tâchez de deviner ce que que Counter a fait

In [ ]:
string_to_vector("Je suis professeur")

Un peu d'aide ...

In [ ]:
# Using Counter with a string
string = "mississippi"
char_count = Counter(string)
print(char_count)

Définition d'une fonction de similarité

In [ ]:
def cosine_similarity(str1, str2):
    # Convert strings to vectors
    vec1 = string_to_vector(str1)
    vec2 = string_to_vector(str2)
    
    # Compute the cosine similarity
    similarity = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
    return similarity

str1 = "hello"
str2 = "yellow"

similarity = cosine_similarity(str1, str2)
print(f"Cosine Similarity: {similarity}")


In [ ]:
!pip install CharVectorizer

ERROR: Could not find a version that satisfies the requirement CharVectorizer (from versions: none)
ERROR: No matching distribution found for CharVectorizer

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: C:\Users\matth\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


**Searching & sorting**

L'approche classique du sorting avec Numpy

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array([[1,4],[3,1]])
np.sort(a)                # sort along the last axis

     # sort along the first axis


In [ ]:
np.sort(a, axis=None)     # sort the flattened array

In [ ]:
np.sort(a, axis=0)   

Préciser sur quel champ réaliser le tri

In [ ]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]
a = np.array(values, dtype=dtype)       # create a structured array
np.sort(a, order='height') 

In [ ]:
pd.DataFrame(a)

In [ ]:
pd.DataFrame(np.sort(a, order='height') )

Testez le code suivant, que se passe-t-il ?

In [ ]:
np.sort(a, order=['age', 'height'])     

Un exemple avec np.where

In [ ]:
import numpy as np

# Creating a sample array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Define the condition
condition = arr > 5

# Find indices where condition is True
indices = np.where(condition)

print("Indices of elements greater than 5:", indices[0])


**Numpy images**

In [ ]:
#pip install opencv-python

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
image=plt.imread("G:/My Drive/Enseignements/Albert School/Cours/Numpy - B1/image.jpg")

In [ ]:
red=image[:,:,0]
plt.imshow(red)

In [ ]:
image[:,:,1]

In [ ]:
plt.imshow(image[:,:,2])

In [ ]:
plt.imshow(image) 

In [ ]:
plt.imshow(np.flipud(image))


In [ ]:
plt.imshow(np.fliplr(image))